README.md, dpl.ts, dpl_test.ts, example/evaluate.ejs, example/evaluate.ts
=> Support evaluate

README.md, dejs.ts, dejs_test.ts, example/basic.ts, example/evaluate.ts
=> Renamed to dejs

README.md, dejs.ts
* Split `compile` and exported it.
=> Split compilation

.travis.yml, README.md
=> Add travis CI config

dejs_test.ts
=> Fixed testing module path

dejs.ts
=> Fixed dependencies

.gitignore, dejs.ts
* Same as title.
* Stopped using global variables.
=> Added scoped variables for template

README.md
* Fix #11.
- 0.1.2 was already released.
=> Release 0.1.3

dejs.ts
* Same as title.
* To avoid conflicting variable names.
=> Use $$FINISHED instead of onFinish

README.md, dejs.ts, dejs_test.ts, example/basic.ts, example/evaluate.ts, example/include.ts
=> Updated to Deno 0.3.0

dejs_test.ts
=> Updated module paths

dejs.ts
=> Fix to handle EOF

dejs.ts
=> update deps links

dejs.ts
* Same as title
* This resolves #24, also resolves #25
=> Fixed to use Deno.EOF

.gitignore, Makefile, dejs.ts, testdata/tsconfig.json
* Same as title.
* This resolves #22
=> Enable strict mode

README.md, dejs_test.ts, example/basic.ts, example/evaluate.ts, example/include.ts, mod.ts
=> Added mod.ts and changed all references to dejs.ts

mod.ts
=> Use UUID to gen random ID

mod.ts, testdata/tsconfig.json
* Same as title
* Deno's local eval is now not broken
* Remove scopeIDs
=> Changed to use local eval

.prettierrc, README.md, dem.json, mod_test.ts, vendor/https/deno.land/std/io/bufio.ts, vendor/https/deno.land/std/io/util.ts, vendor/https/deno.land/std/testing/asserts.ts, vendor/https/deno.land/std/testing/mod.ts
=> Release 0.3.5

.github/workflows/test.yml, .prettierrc, Makefile, README.md, dejs.ts, dem.json, mod.ts, mod_test.ts, vendor/https/deno.land/std/io/bufio.ts, vendor/https/deno.land/std/io/util.ts, vendor/https/deno.land/std/testing/asserts.ts
* Support Deno v0.42.0
* Add fmt / lint
- Removed .prettierrc
=> Release 0.4.0

README.md
* Added description of dem.
* Added descriptions of newly added make commands.
=> Improved Development section of README.md

mod.ts
=> Use Function() instead of eval()

README.md, mod.ts, mod_test.ts
* Added sanitizing for template string litelals.
* Reported on  #47
=> Add sanitizing for template string

README.md, mod.ts
* This will provide solution for #40.
=> Add renderToString and renderFileToString

README.md, example/basic.ts, example/evaluate.ts, example/include.ts
`copy` function interface has been changed.
=> Fix examples using copy

README.md, dem.json
* Support template pattern reported on #54.
=> Release 0.7.0

README.md, dem.json, vendor/https/deno.land/std/encoding/utf8.ts, vendor/https/deno.land/std/io/bufio.ts, vendor/https/deno.land/std/io/readers.ts, vendor/https/deno.land/std/testing/asserts.ts
=> Release 0.9.0

README.md, dem.json, vendor/https/deno.land/std/encoding/utf8.ts, vendor/https/deno.land/std/io/bufio.ts, vendor/https/deno.land/std/io/readers.ts, vendor/https/deno.land/std/testing/asserts.ts
=> Release 0.9.1

README.md
* To investigate version not found issue on deno.land
=> Release 0.9.2

mod.ts, mod_test.ts
=> support overriding include func

LICENSE.md, README.md, dem.json, egg.json, mod_test.ts, vendor/https/deno.land/std/io/buffer.ts, vendor/https/deno.land/std/io/bufio.ts, vendor/https/deno.land/std/io/util.ts, vendor/https/deno.land/std/testing/asserts.ts
=> Release 0.10.3
